version: '3'
services:
  petclinic-app:
    image: openjdk:17
    ports:
      - 8080:8080
    volumes:
      - ./target/spring-petclinic-3.1.0-SNAPSHOT.jar:/home/spring-petclinic-3.1.0-SNAPSHOT.jar
    command: ["java", "-jar", "/home/spring-petclinic-3.1.0-SNAPSHOT.jar"]
  petclinic-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
