version: '3'
services:
  petclinic-app:
    image: openjdk:17-jdk-alpine
    container_name: petclinic-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petclinic?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: petclinic-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
